# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "df5796e07bd3899b54f11db327f9d4b3"
name = "app-zoy"
handle = "app-zoy"
application_url = "https://clusters-lecture-focal-wrist.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://clusters-lecture-focal-wrist.trycloudflare.com/auth/callback",
  "https://clusters-lecture-focal-wrist.trycloudflare.com/auth/shopify/callback",
  "https://clusters-lecture-focal-wrist.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
